# Generated by Django 4.0.5 on 2022-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabañas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Cabaña')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('personas', models.CharField(max_length=50, verbose_name='Numero maximo de personas')),
                ('camas', models.CharField(max_length=50, verbose_name='Numero de Camas')),
                ('costo', models.CharField(max_length=50, verbose_name='Costo por día')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen del Curso')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cabañas',
                'verbose_name_plural': 'Cabañas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='promociones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombreAlumno', models.CharField(max_length=50, verbose_name='Nombre del Alumno')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['created'],
            },
        ),
    ]
