# Generated by Django 4.0.5 on 2022-08-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promociones',
            options={'ordering': ['created'], 'verbose_name': 'Promociones', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.RemoveField(
            model_name='promociones',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='promociones',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='promociones',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='promociones',
            name='nombreAlumno',
        ),
        migrations.RemoveField(
            model_name='promociones',
            name='nota',
        ),
        migrations.AddField(
            model_name='promociones',
            name='descripcionPromo',
            field=models.CharField(default=100, max_length=50, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promociones',
            name='imagenPromo',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotos'),
        ),
        migrations.AddField(
            model_name='promociones',
            name='nombrePromo',
            field=models.CharField(default=2, max_length=50, verbose_name='Nombre de la Cabañas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabañas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotos'),
        ),
    ]
