# Generated by Django 4.0.5 on 2022-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0002_alter_promociones_options_remove_promociones_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promociones',
            name='nombrePromo',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Cabaña'),
        ),
    ]
