# Generated by Django 4.0.5 on 2022-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0003_alter_promociones_nombrepromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='costoPromo',
            field=models.CharField(default=1, max_length=50, verbose_name='Costo de promoción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promociones',
            name='descripcionPromo',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
