# Generated by Django 4.0.5 on 2022-08-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0004_promociones_costopromo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombreClien', models.CharField(max_length=50, verbose_name='Nombre del Cliente')),
                ('nombreCabaña', models.CharField(max_length=50, verbose_name='Nombre de la Cabaña')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('duda', models.TextField(verbose_name='Duda')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Subido')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Opinion',
                'verbose_name_plural': 'Opinion',
                'ordering': ['created'],
            },
        ),
    ]
