# Generated by Django 4.0.5 on 2022-08-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0005_opinion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['created'], 'verbose_name': 'Opiniones', 'verbose_name_plural': 'Opiniones'},
        ),
        migrations.AddField(
            model_name='opinion',
            name='imagenOp',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotos'),
        ),
    ]
